'use client'

import { FileText, Copy, Check, ArrowLeft, Download, Building } from 'lucide-react'
import Link from 'next/link'
import { useState } from 'react'
import { motion, AnimatePresence } from 'framer-motion'
import { FadeIn, ScaleHover } from '@/components/Animated'

export default function MOUPage() {
    const [copied, setCopied] = useState(false)

    const mouText = `# MEMORANDUM OF UNDERSTANDING (MOU)
## FOR INSTITUTIONAL PILOT PROGRAMME

**BETWEEN:**
**EduPulse Intelligence** (The "Provider")
**AND:**
**[INSTITUTION NAME]** (The "Partner Institution")

### 1. PURPOSE
The purpose of this MOU is to outline the terms of a 3-month strategic pilot of the EduPulse real-time feedback platform within selected courses at the Partner Institution.

### 2. SCOPE OF PILOT
*   **Duration**: 90 Days from [START DATE].
*   **Scale**: Up to [NUMBER] unique classrooms/educators.
*   **Technology**: Provision of Educator Dashboards and the Pilot-Verified Student Pulse Interface.

### 3. RESPONSIBILITIES
*   **Provider**: Shall provide technical support, educator onboarding, and weekly "Pedagogical Insight" reports generated by the EduPulse AI engine.
*   **Institution**: Shall encourage student participation and provide feedback on the platform's impact on classroom engagement and retention.

### 4. DATA & PRIVACY (ZERO-PII PROMISE)
*   **Ownership**: The Institution retains ownership of all pedagogical signals generated.
*   **Privacy**: Provider guarantees a **Zero-PII Architecture**. No student names, emails, or personal identifiers shall be collected or stored. All signals are processed anonymously via session-specific tokens.
*   **Compliance**: The system is aligned with UGC 2024 (India) and FERPA/GDPR (International) standards for data safety.

### 5. CONFIDENTIALITY
Both parties agree to treat the data generated during the pilot as confidential and will not share specific institutional insights with third parties without written consent.

### 6. TERMINATION
Either party may terminate the pilot with 7 days' written notice if the platform does not meet pedagogical objectives.

---
**SIGNATORIES:**

__________________________          __________________________
**EduPulse Intelligence**            **[INSTITUTION NAME]**
Date: ______________                 Date: ______________`

    const handleCopy = () => {
        navigator.clipboard.writeText(mouText)
        setCopied(true)
        setTimeout(() => setCopied(false), 2000)
    }

    return (
        <div style={{ minHeight: '100vh', background: 'var(--bg-base)', color: 'var(--text-primary)', fontFamily: 'var(--font-body)', position: 'relative', overflow: 'hidden' }}>
            
            {/* Ambient glows */}
            <div style={{ position: 'fixed', inset: 0, pointerEvents: 'none', zIndex: 0 }}>
                <div style={{ position: 'absolute', top: '10%', left: '0%', width: '30%', height: '30%', background: 'radial-gradient(ellipse, rgba(99,102,241,0.03) 0%, transparent 70%)' }} />
                <div style={{ position: 'absolute', bottom: '10%', right: '0%', width: '40%', height: '40%', background: 'radial-gradient(ellipse, rgba(79,70,229,0.02) 0%, transparent 70%)' }} />
            </div>

            {/* Header */}
            <header style={{ borderBottom: '1px solid var(--border)', height: 56, display: 'flex', alignItems: 'center', padding: '0 1.75rem', gap: '0.75rem', backdropFilter: 'blur(24px)', position: 'sticky', top: 0, zIndex: 10, background: 'var(--glass-bg)' }}>
                <Link href="/" style={{ display: 'flex', alignItems: 'center', gap: '0.375rem', color: 'var(--text-secondary)', textDecoration: 'none', fontSize: '0.857rem', fontWeight: 500 }}>
                    <ArrowLeft size={14} /> Home
                </Link>
                <span style={{ color: 'var(--text-tertiary)' }}>/</span>
                <span style={{ fontFamily: 'var(--font-display)', fontWeight: 700, fontSize: '0.9rem', color: 'var(--text-primary)' }}>MOU Template</span>
                <div style={{ flex: 1 }} />
                <div className="section-label" style={{ opacity: 0.8 }}>Institutional Trust Center</div>
            </header>

            <main style={{ maxWidth: 900, margin: '0 auto', padding: '4rem 1.75rem', position: 'relative', zIndex: 1 }}>
                
                <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'flex-end', marginBottom: '3rem', flexWrap: 'wrap', gap: '2rem' }}>
                    <FadeIn>
                        <div style={{ display: 'flex', alignItems: 'center', gap: '0.8rem', marginBottom: '1rem' }}>
                            <div style={{ width: 40, height: 40, background: 'var(--accent-dim)', borderRadius: 10, display: 'flex', alignItems: 'center', justifyContent: 'center', border: '1px solid var(--border-accent)' }}>
                                <FileText size={20} color="var(--accent-soft)" />
                            </div>
                            <span style={{ fontSize: '0.8rem', fontWeight: 700, letterSpacing: '0.1em', color: 'var(--text-tertiary)', textTransform: 'uppercase' }}>Legal Documentation</span>
                        </div>
                        <h1 style={{ fontFamily: 'var(--font-display)', fontSize: 'clamp(2rem, 4.5vw, 3rem)', fontWeight: 700, letterSpacing: '-0.04em' }}>
                            Pilot MOU <span className="gradient-text">Template.</span>
                        </h1>
                        <p style={{ color: 'var(--text-secondary)', fontSize: '1rem', marginTop: '0.5rem', maxWidth: 500 }}>
                            A formal framework for a 90-day institutional pilot. Ready for your legal department’s review.
                        </p>
                    </FadeIn>
                    
                    <FadeIn delay={0.2} style={{ display: 'flex', gap: '0.75rem' }}>
                        <ScaleHover>
                            <button onClick={handleCopy} className="btn-ghost" style={{ display: 'flex', alignItems: 'center', gap: '0.5rem', background: 'var(--bg-elevated)', padding: '0.75rem 1.25rem' }}>
                                <AnimatePresence mode="wait">
                                    {copied ? <Check size={16} key="check" /> : <Copy size={16} key="copy" />}
                                </AnimatePresence>
                                {copied ? 'Copied!' : 'Copy Template'}
                            </button>
                        </ScaleHover>
                        <ScaleHover>
                            <button onClick={() => window.print()} className="btn-primary" style={{ display: 'flex', alignItems: 'center', gap: '0.5rem', padding: '0.75rem 1.25rem' }}>
                                <Download size={16} /> Download PDF
                            </button>
                        </ScaleHover>
                    </FadeIn>
                </div>

                {/* Document Paper Section */}
                <FadeIn delay={0.3}>
                    <div style={{ 
                        background: '#ffffff', 
                        color: '#1a1a1a', 
                        padding: 'max(2rem, 5vw) max(1rem, 6vw)', 
                        borderRadius: 4, 
                        boxShadow: '0 25px 50px -12px rgba(0,0,0,0.5)', 
                        fontFamily: 'serif', 
                        lineHeight: 1.6,
                        border: '1px solid #e5e5e5',
                        position: 'relative'
                    }}>
                        {/* Watermark/Seal */}
                        <div style={{ position: 'absolute', top: '2rem', right: '3rem', opacity: 0.05, pointerEvents: 'none' }}>
                            <Building size={160} />
                        </div>

                        <div style={{ textAlign: 'center', marginBottom: '3rem', borderBottom: '2px solid #1a1a1a', paddingBottom: '1.5rem' }}>
                            <h2 style={{ fontSize: '1.75rem', fontWeight: 800, margin: 0, letterSpacing: '0.05em' }}>MEMORANDUM OF UNDERSTANDING</h2>
                            <p style={{ margin: '0.5rem 0 0', fontWeight: 600, color: '#666' }}>FOR INSTITUTIONAL PILOT PROGRAMME</p>
                        </div>

                        <div style={{ marginBottom: '2rem' }}>
                            <p><strong>BETWEEN:</strong></p>
                            <p style={{ paddingLeft: '2rem' }}><strong>EduPulse Intelligence</strong>, having its principal place of business at EDVentures Delhi, India (hereinafter referred to as the "Provider")</p>
                            <p><strong>AND:</strong></p>
                            <p style={{ paddingLeft: '2rem', borderBottom: '1px dotted #1a1a1a', display: 'inline-block', minWidth: '300px' }}><strong>[INSTITUTION NAME]</strong> (hereinafter referred to as the "Partner Institution")</p>
                        </div>

                        <section style={{ marginBottom: '2.5rem' }}>
                            <h3 style={{ fontSize: '1.2rem', textTransform: 'uppercase', borderBottom: '1px solid #eee', paddingBottom: '0.5rem', marginBottom: '1rem' }}>1. PURPOSE</h3>
                            <p>The purpose of this MOU is to outline the terms of a 3-month strategic pilot of the EduPulse real-time feedback platform within selected courses at the Partner Institution.</p>
                        </section>

                        <section style={{ marginBottom: '2.5rem' }}>
                            <h3 style={{ fontSize: '1.2rem', textTransform: 'uppercase', borderBottom: '1px solid #eee', paddingBottom: '0.5rem', marginBottom: '1rem' }}>2. SCOPE OF PILOT</h3>
                            <ul style={{ paddingLeft: '1.5rem' }}>
                                <li style={{ marginBottom: '0.5rem' }}><strong>Duration</strong>: 90 Days from [START DATE].</li>
                                <li style={{ marginBottom: '0.5rem' }}><strong>Scale</strong>: Up to [NUMBER] unique classrooms/educators.</li>
                                <li style={{ marginBottom: '0.5rem' }}><strong>Technology</strong>: Provision of Educator Dashboards and the Pilot-Verified Student Pulse Interface.</li>
                            </ul>
                        </section>

                        <section style={{ marginBottom: '2.5rem' }}>
                            <h3 style={{ fontSize: '1.2rem', textTransform: 'uppercase', borderBottom: '1px solid #eee', paddingBottom: '0.5rem', marginBottom: '1rem' }}>3. RESPONSIBILITIES</h3>
                            <p><strong>Provider</strong> shall provide technical support, educator onboarding, and weekly "Pedagogical Insight" reports generated by the EduPulse AI engine.</p>
                            <p><strong>Institution</strong> shall encourage student participation and provide feedback on the platform's impact on classroom engagement and retention.</p>
                        </section>

                        <section style={{ marginBottom: '2.5rem' }}>
                            <h3 style={{ fontSize: '1.2rem', textTransform: 'uppercase', borderBottom: '1px solid #eee', paddingBottom: '0.5rem', marginBottom: '1rem' }}>4. DATA & PRIVACY (ZERO-PII PROMISE)</h3>
                            <p><strong>Ownership</strong>: The Institution retains ownership of all pedagogical signals generated during the pilot phase.</p>
                            <p><strong>Privacy</strong>: Provider guarantees a <strong>Zero-PII Architecture</strong>. No student names, emails, or personal identifiers shall be collected or stored. All signals are processed anonymously via session-specific tokens.</p>
                            <p><strong>Compliance</strong>: The system is aligned with UGC 2024 (India) and FERPA/GDPR (International) standards for data safety.</p>
                        </section>

                        <section style={{ marginBottom: '2.5rem' }}>
                            <h3 style={{ fontSize: '1.2rem', textTransform: 'uppercase', borderBottom: '1px solid #eee', paddingBottom: '0.5rem', marginBottom: '1rem' }}>5. DIGITAL AUTHORIZATION & VERIFICATION</h3>
                            <p>This framework is digitally pre-verified and authorized by **EduPulse Intelligence**. By initiating an institutional pilot session, the Provider acknowledges and accepts all responsibilities outlined herein.</p>
                            <div style={{ marginTop: '1.5rem', padding: '1rem', border: '1px solid #eee', background: '#f9f9f9', borderRadius: '4px' }}>
                                <p style={{ margin: '0', fontSize: '0.9rem' }}><strong>Authorized by:</strong> EduPulse Legal & Compliance Dept.</p>
                                <p style={{ margin: '0.2rem 0 0', fontSize: '0.9rem' }}><strong>Authorization ID:</strong> EP-AUTH-2026-PILOT-82</p>
                                <p style={{ margin: '0.2rem 0 0', fontSize: '0.9rem' }}><strong>Status:</strong> <span style={{ color: '#059669', fontWeight: 800 }}>ACTIVE & VERIFIED</span></p>
                            </div>
                        </section>

                        <section style={{ marginBottom: '2.5rem' }}>
                            <h3 style={{ fontSize: '1.2rem', textTransform: 'uppercase', borderBottom: '1px solid #eee', paddingBottom: '0.5rem', marginBottom: '1rem' }}>6. CONFIDENTIALITY</h3>
                            <p>Both parties agree to treat the data generated during the pilot as confidential and will not share specific institutional insights with third parties without written consent.</p>
                        </section>

                        <section style={{ marginBottom: '2.5rem' }}>
                            <h3 style={{ fontSize: '1.2rem', textTransform: 'uppercase', borderBottom: '1px solid #eee', paddingBottom: '0.5rem', marginBottom: '1rem' }}>7. TERMINATION</h3>
                            <p>Either party may terminate the pilot with 7 days' written notice if the platform does not meet pedagogical objectives.</p>
                        </section>
                    </div>
                </FadeIn>

                <footer style={{ marginTop: '4rem', textAlign: 'center', color: 'var(--text-tertiary)', fontSize: '0.8rem' }}>
                    Reference ID: EP-MOU-2026-V1 · EduPulse Trust Center
                </footer>

            </main>
        </div>
    )
}
